### ISSUE TITLE
Names in multiple languages

### ISSUE THREAD

**Issue by pnorman** [pnorman/ClearTables#25]
There are three obvious options for adding multi-lingual names
1. Add a fixed list of columns (e.g. `name_en`) which are populated from the `name` tag and `name:en` etc, roughly with `cols.name_en = tags["name:en"] or tags["name"] or nil`
2. Add a fixed list of columns (e.g. `name_en`, `name_de`) which contain the `name:en`, etc tag values
3. Add a name_int hstore column with all alternate-language names. `cols.name_int = "en=>"..tags["name:en"]` extended to arbitrary languages.

1 and 2 can't handle arbitrary lists of languages. 2 and 3 require stylesheet logic for fallback names if you want to default to another language, e.g. `COALESCE(name_en,name) AS name`

cc @yurik, @maxsem, since I know they've looked at international languages

**Comment by MaxSem** [comment]
OSM supports many languages (in theory, every language with an ISO 639 code), so fixed columns will not work.
